
# Group Tasks CRUD

CRUD API.

## Tasks [/task/*]

### Retrieve index [GET /task]

+ Request

    + Headers

            Authorization: Bearer {{ACCESS_TOKEN}}

+ Response 200 (application/json)

        {
            "data": [{
                "id": "1",
                "label": "do something...",
                "done": true
            }, {
                "id": "2",
                "label": "do something else ...",
                "done": false
            }]
        }

+ Response 401 (application/json)

        {
            "code": "Unauthenticated",
            "message": "Not authenticated"
        }

### Retrieve item [GET /task/{id}]

+ Parameters

    + id: `0` (number, optional) - item id.

+ Request

    + Headers

            Authorization: Bearer {{ACCESS_TOKEN}}

+ Response 200 (application/json)

        {
            "data": {
                "id": "1",
                "label": "do something...",
                "done": true
            }
        }

+ Response 401 (application/json)

        {
            "code": "Unauthenticated",
            "message": "Not authenticated"
        }


