FORMAT: 1A
HOST: http://api.example.com

# Sample API

<!-- include(./spec-auth.apib) -->

<!-- include(./spec-crud.apib) -->

<!-- include(./spec-indexing.apib) -->

<!-- include(./spec-draft.apib) -->
