version: '2.3'

services:

  pgadmin:
    image: dpage/pgadmin4:3
    hostname: pgadmin
    ports:
      - 1101:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin
      PGADMIN_DEFAULT_PASSWORD: pgadmin

# => http://localhost:1101/
